// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/21/2026, 1:07:25 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/macbook/Web Workspace/LeadHeat/leadheat/apps/web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macbook/Web Workspace/LeadHeat/leadheat/apps/web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macbook/Web Workspace/LeadHeat/leadheat/apps/web/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macbook/Web Workspace/LeadHeat/leadheat/apps/web/plugins/**/*.{js,ts,mjs}","/Users/macbook/Web Workspace/LeadHeat/leadheat/apps/web/composables/**/*.{js,ts,mjs}","/Users/macbook/Web Workspace/LeadHeat/leadheat/apps/web/utils/**/*.{js,ts,mjs}","/Users/macbook/Web Workspace/LeadHeat/leadheat/apps/web/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macbook/Web Workspace/LeadHeat/leadheat/apps/web/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/macbook/Web Workspace/LeadHeat/leadheat/apps/web/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/macbook/Web Workspace/LeadHeat/leadheat/apps/web/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;